name: CI/CD for NoteKeeper

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set environment variables
        run: |
          echo "REACT_APP_APPWRITE_API_KEY=${{ secrets.REACT_APP_APPWRITE_API_KEY }}" >> $GITHUB_ENV
          echo "REACT_APP_APPWRITE_COLLECTION_ID=${{ secrets.REACT_APP_APPWRITE_COLLECTION_ID }}" >> $GITHUB_ENV
          echo "REACT_APP_APPWRITE_DATABASE_ID=${{ secrets.REACT_APP_APPWRITE_DATABASE_ID }}" >> $GITHUB_ENV
          echo "REACT_APP_APPWRITE_ENDPOINT=${{ secrets.REACT_APP_APPWRITE_ENDPOINT }}" >> $GITHUB_ENV
          echo "REACT_APP_APPWRITE_PROJECT_ID=${{ secrets.REACT_APP_APPWRITE_PROJECT_ID }}" >> $GITHUB_ENV

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test

      - name: Build project
        run: npm run build

      - name: Deploy to Vercel
        run: vercel --token ${{ secrets.VERCEL_TOKEN }} --prod
